services:
  backend-admin-db:
    image: mysql:8.0
    container_name: backend-admin-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jensen # Only define the root password
      MYSQL_DATABASE: jensen2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
