### Set Global Token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzZjk3MzNmLWM5NjktNGQyMy05N2UyLWI0ZDA4YzAxM2QwZCIsInVzZXJuYW1lIjoiamFtYSIsImdyb3VwcyI6W10sImlhdCI6MTczMjg0Mzk4MiwiZXhwIjoxNzMyODQ0ODgyfQ.3Y_9s9u8OaVSoXJFfBZhqIK4_lh7qxTlEcek9q4zZZg


### Create user Request
POST http://localhost:3000/api/admin/users
Content-Type: application/json


{
   "username": "jama",
   "password": "asdfgh",
   "role": "user",
   "grupp": "Ismails grupp",
   "field": "developer"
}


### Delete users by ID Request
DELETE http://localhost:3000/api/admin/users/7da34c27-154e-4051-9df2-072204890d60
Content-Type: application/json
Authorization: Bearer {{token}}


### Login Request
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "username": "jama",
   "password": "asdfgh"
}



### Get all Posts Request
GET http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}



### Create POST Request
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "content": "jama jama majam majaa...",
   "category": "Docker test is continuing"
}


### Delete post by ID Request
DELETE http://localhost:3000/api/posts/2b738c34-f6dc-4228-9450-5b6de311bf40
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "username": "ahmed",
   "password": "asdfgh"
}